FROM golang:1.9-alpine3.7

LABEL maintainer="Austin J. Alexander <aja@design-brain.com>"

RUN apk add --update --no-cache build-base git

COPY . /go/src/github.com/design-brain/images-api
WORKDIR /go/src/github.com/design-brain/images-api

ENV ENVIRONMENT=linting

RUN go get -u github.com/alecthomas/gometalinter
RUN gometalinter --config=.gometalinter.json --install

RUN make lint
